### ISSUE TITLE
Рекламный скрипт

### ISSUE THREAD

**Issue by egurevich** [strizhas/media_scripts#2]
На данный момент у нас есть вот такой скрипт, который подгоняет любые ролики под рекламные тт (смотри пдф), а также спрашивает нужно ли сделать версию для мобильных (те же требования, но битрейт чуть меньше). 
Периодически появляется необходимость сделать ролик для Smart TV, там все те же требования, но размер должен быть строго 1280х720 и я бы поднял для них битрейт до 3.5 мбпс. 
Думаю, можно сделать единый рекламный скрипт, справляющийся с каждой из этих трех задач (web, mobile, smarttv)

[Технические требования_IVI RU.pdf](https://github.com/strizhas/media_scripts/files/526794/_IVI.RU.pdf)

[adv_script_v3.command.zip](https://github.com/strizhas/media_scripts/files/526792/adv_script_v3.command.zip)

**Comment by strizhas** [comment]
Внёс соответствующие исправления в скрипт и для удобства вынес его в отдельный репозиторий https://github.com/strizhas/adv_script
